name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: setup go v1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.6

    - name: docker version
      run: |
        docker version

    - name: setup buildx
      run: |
        mkdir -p ~/.docker/cli-plugins
        curl -L -s https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 \
          -o ~/.docker/cli-plugins/docker-buildx
        chmod a+x ~/.docker/cli-plugins/docker-buildx
        echo '{"experimental": "enabled"}' > ~/.docker/config.json
        cat ~/.docker/config.json
        docker buildx version

    - name: build app
      run: |
        go build -o app

    - name: build docker image
      run: |
        docker buildx build --name test-app .

    - name: test the image
      run: |
        docker run --rm test-app
