name: CI

on: [push]

env:
  BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: setup go v1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.6

    - name: setup buildx
      run: |
        mkdir -p $HOME/.docker/cli-plugins
        curl -L -s $BUILDX_URL -o $HOME/.docker/cli-plugins/docker-buildx
        chmod a+x $HOME/.docker/cli-plugins/docker-buildx
        echo '{"experimental": "enabled"}' > $HOME/.docker/config.json
        docker buildx version

    - name: build app
      run: |
        go build -o app

    - name: docker Login
      run: echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: $GITHUB_ACTOR
        
    - name: build docker image
      env:
        GITHUB_REPOSITORY: $GITHUB_REPOSITORY
      run: |
        echo $GITHUB_REPOSITORY
        docker buildx build --push --platform linux/arm/v7 -t docker.pkg.github.com/${GITHUB_REPOSITORY}/hello-world:0.0.1 .

    - name: test the image
      env:
        GITHUB_REPOSITORY: $GITHUB_REPOSITORY
      run: |
        docker run --rm docker.pkg.github.com/${GITHUB_REPOSITORY}/hello-world:0.0.1
