name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: change go version
      run: |
        export GOROOT=/usr/local/go1.13
        go env
        go build -o app

    - name: docker version
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker buildx build .
        docker buildx build -o type=docker --name test-app .
        docker run --rm test-app
