name: CI

on: [push]

env:
  BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: setup go v1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.6

    - name: setup buildx
      run: |
        mkdir -p $HOME/.docker/cli-plugins
        curl -L -s $BUILDX_URL -o $HOME/.docker/cli-plugins/docker-buildx
        chmod a+x $HOME/.docker/cli-plugins/docker-buildx
        echo '{"experimental": "enabled"}' > $HOME/.docker/config.json
        docker buildx version

    - name: build app
      run: |
        go build -o app

    - name: build docker image
      run: |
        docker buildx build --platform linux/amd64 -t my-docker-image .

    - name: test the image
      run: |
        docker run --rm my-docker-image
