name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: change go version
      run: |
        go env
        export GOROOT=/usr/local/go1.13
        go env

    - name: docker version
      run: |
        docker version
        docker buildx build .
