name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: setup go v1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.6

    - name: build app
      run: |
        go build -o app

    - name: docker version
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker buildx build -o type=docker --name test-app .
        docker run --rm test-app
