name: CI

on: [push]

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: setup go v1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.6

    - name: setup buildx
      run: |
        mkdir -p ~/.docker/cli-plugins
        curl -s -o ~/.docker/cli-plugins/docker-buildx \
          https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64

    - name: build app
      run: |
        go build -o app

    - name: build docker image
      run: |
        docker buildx build -o type=docker --name test-app .

    - name: test the image
      run: |
        docker run --rm test-app
